import 'package:flutter/material.dart';

const Color colorGreyTetiary=Color(0xFF8492A6);
const Color colorGreySecond=Color(0xF9444F66);
const Color colorGreyPri=Color(0xFF2F3845);
const Color colorGreyDisable=Color(0xFFEAEDF1);
const Color colorMainTealPri=Color(0xFF1CBA92);
const Color colorWaringText=Color(0xB3F29303);
const Color colorMainBlue=Color(0xFF2265C6);
const Color colorAccentBlue=Color(0xFF1258B0);
const Color colorSystemWhite=Color(0xFFFFFFFF);
const Color colorBGInput=Color(0xFFF1F5F8);
const Color colorErrorPrimary=Color(0xF0E12424);
const Color colorBlueQuaternery=Color(0xFFD9E7FA);
const Color colorBGSkip=Color(0xFF252A31);
const Color colorGrayBG=Color(0xB88492A6);
const Color colorMainBlueClick=Color(0x4d0b418f);
const Color colorGreyDevi=Color(0xffdfe9f5);
const Color colorSystemErrorTer=Color(0xfffff2f9);
const Color colorSystemPurpleTertiary =Color(0xffe5e0ff);
const Color colorSystemPurple=Color(0xff5f2dd6);
const Color colorMainBlueChart=Color(0xff3a7de0);
const Color colorSystemAtten=Color(0xfff29303);
const Color colorSystemYeloow=Color(0xfff4b40f);